export { Navbar } from './navbar'
export { HeroSection } from './HeroSection'
export { AboutSection } from './AboutSection'
export { GamesSection } from './GameSection'
export { FeaturesSection } from './FeatureSection'
export { CommunitySection } from './CommunitySection'
export { DealsSection } from './DealSection'
export { Footer } from './footer'
